# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20170604_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
