# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_user_other_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='other_name2',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
