# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_user_other_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('other_name', models.CharField(max_length=30, null=True)),
                ('other_name2', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'users2',
            },
        ),
    ]
