# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_user2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User2',
        ),
    ]
