# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_delete_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='other_name2',
        ),
    ]
